markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
  
title: [Automotive Grade Linux Documantation Link]
description: [Documentation link for the passed AGL All Member Meeting, Automotive Linux Summit and other.]

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
